name: Deploy to AWS SAM

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [closed]

env:
  AWS_REGION: ${{ secrets.AWS_PROJECT_REGION }}
  STACK_NAME: ever-smile-ai-dev
  ENVIRONMENT: dev

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "src/api/package-lock.json"

      - name: Install dependencies
        run: |
          cd src/api
          npm ci

      - name: Validate SAM template
        run: sam validate

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM application
        run: sam build

      - name: Deploy to AWS
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }} \
            --parameter-overrides Stage=${{ env.ENVIRONMENT }} \
            --stage ${{ env.ENVIRONMENT }}

      - name: Get deployment status
        run: |
          echo "${{ env.ENVIRONMENT }} deployment completed successfully!"
          echo "Stack: ${{ env.STACK_NAME }}"
          echo "Region: ${{ env.AWS_REGION }}"
