name: Deploy to AWS SAM - Dev Branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/deploy-sam.yml
    with:
      stack-name: ever-smile-ai-dev
      environment: dev
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_PROJECT_REGION }}
