name: Deploy SAM Application

on:
  workflow_call:
    inputs:
      stack-name:
        description: "Name of the CloudFormation stack to deploy"
        required: true
        type: string
      environment:
        description: "Environment name (dev/prod)"
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

env:
  AWS_REGION: ${{ secrets.aws-region }}
  STACK_NAME: ${{ inputs.stack-name }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "src/api/package-lock.json"

      - name: Install dependencies
        run: |
          cd src/api
          npm ci

      - name: Validate SAM template
        run: sam validate

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM application
        run: sam build

      - name: Deploy to AWS
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }} \
            --parameter-overrides Stage=${{ env.ENVIRONMENT }} \
            --stage ${{ env.ENVIRONMENT }}

      - name: Get deployment status
        run: |
          echo "${{ env.ENVIRONMENT }} deployment completed successfully!"
          echo "Stack: ${{ env.STACK_NAME }}"
          echo "Region: ${{ env.AWS_REGION }}"
